### ISSUE TITLE
Roadmap for v0.1

### ISSUE THREAD

**Issue by luzhlon** [luzhlon/vwm.nvim#1]
Session utility:
* [x] save/load session files, left-panel.
* [x] load local configuration. Such as `.vim/settings.vim`, it's can be customized.
* [x] `g:vwm#ss#ignore` ignore specified directories

Bookmarks utility:
* [x] add/remove bookmark with label support.
* [x] list all bookmarks in quickfix window.
* [x] keymap: BookmarkPrev/BookmarkNext

Check for Temporary file:
* [x] italic name in bufline
* [x] check for Temporary file

Document:
* [x] vim's help
* [x] ScreenShots

**Comment by luzhlon** [comment]
Content need to add to doc:
* coc.nvim & gina.vim to show bottom status
* download link for neovim 0.4.0-982+, depends `sign_xxx()`
* depends **ripgrep**
